# Generated by Django 4.2.26 on 2025-11-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_sats',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
