# Generated by Django 4.2.26 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_amount_sats'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='tx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
