# Generated by Django 4.2.26 on 2025-12-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_funding_tx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ln_invoice',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
