# Generated by Django 4.2.26 on 2025-11-11 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_task_created_at_task_rewarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('current_city', models.CharField(blank=True, max_length=100, verbose_name='Ville actuelle')),
                ('work_mode', models.CharField(choices=[('onsite', 'En Présentiel'), ('remote', 'En Télétravail (Remote)'), ('hybrid', 'Hybride'), ('travel', 'Disposé à voyager')], default='remote', max_length=30, verbose_name='Moyen de travail')),
                ('availability', models.CharField(choices=[('full_time', 'Plein temps'), ('part_time', 'Temps partiel'), ('hourly', "À l'heure"), ('project', 'Par projet')], default='project', max_length=30, verbose_name='Disponibilité')),
                ('profile_picture_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='users', to='projects.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
