# Generated by Django 4.2.26 on 2025-11-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_skill_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil Utilisateur', 'verbose_name_plural': 'Profils Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/pictures/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Image de couverture'),
        ),
    ]
