# Generated by Django 4.2.26 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_invitation_options_invitation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
